[build]
  publish = "dist"
  command = "bun run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "bun run build"

[context.deploy-preview]
  command = "bun run build"

[context.branch-deploy]
  command = "bun run build"
